# Main config file
title: "notate"
description: "A documentation framework for rapid rollout of style guides and component / pattern libraries."
repo: "https://github.com/Stenners/Notate"
homepage: ""
version: "0.1.0"

# Project imports
imports:
  css: 
    - src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
  js:
    - src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"

# These sections will become the nav
sections:
  - title: "Colour"
    slug: "colour"
    content: "pages/styleguide/colour.md"

  - title: "Typography"
    slug: "typography"
    content: "pages/styleguide/typography.md"

  - heading: "Components" # Not sure about this implementation

  - title: "Alerts"
    slug: "alerts"
    content: "pages/components/alerts.md"
    
  - title: "Buttons"
    slug: "buttons"
    content: "pages/components/buttons.md"

  - title: "Collapse"
    slug: "collapse"
    content: "pages/components/collapse.md"