# Main config file
title: "Component library demo"
theme: "src/themes/swanky-theme"
layouts: "src/themes/swanky-theme/templates/layouts"
partials: "src/themes/swanky-theme/templates/partials"
snippets: "src/snippets"
version: "0.0.0"

# These sections will become the nav
sections:
  - title: "Typography"
    slug: "typography"
    content: "pages/styleguide/typography.md"

  - title: "Colour"
    slug: "colour"
    content: "pages/styleguide/colour.md"

  - title: "Components"
    slug: "components"
    content:
      - title: 'Buttons'
        src: 'pages/components/buttons.md'
      - title: 'Alerts'
        src: 'pages/components/alerts.md'

  - title: "Markdown Cheatsheet"
    slug: "markdown"
    content: "pages/markdown.md"