# Main config file
title: "Component library demo"
theme: "src/themes/swanky-theme"
layouts: "src/themes/swanky-theme/templates/layouts"
partials: "src/themes/swanky-theme/templates/partials"
snippets: "src/snippets"
version: "0.0.0"

# Project imports
imports:
  css: 
    - src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    - src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.other.css"
  js:
    - src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"

# These sections will become the nav
sections:
  - title: "Colour"
    slug: "colour"
    content: "pages/styleguide/colour.md"

  - title: "Typography"
    slug: "typography"
    content: "pages/styleguide/typography.md"

  - heading: "Components" # Not sure about this implementation

  - title: "Alerts"
    slug: "alerts"
    content: "pages/components/alerts.md"
    
  - title: "Buttons"
    slug: "buttons"
    content: "pages/components/buttons.md"

  - title: "Collapse"
    slug: "collapse"
    content: "pages/components/collapse.md"